version: '3.8'

services:
  mysql:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=senha123
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=rodox
      - MYSQL_PASSWORD=senha123
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  adminer:
    container_name: admin
    image: adminer:4
    ports:
      - 8080:8080

  symfony:
    container_name: api
    build:
      context: .
    environment:
      - DATABASE_URL=mysql://root:senha123@db/symfony
    ports:
      - 8000:8000
    volumes:
      - ./:/api
    depends_on:
      - mysql
      - adminer
    command: ["symfony", "server:start"]

volumes:
  db:
